# Generated by Django 5.1 on 2024-10-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
