# Generated by Django 5.1 on 2024-10-13 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_price_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='details_text_editor',
        ),
    ]
