services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
        APP_PORT: ${APP_PORT:-8000}
    env_file:
      - .env
    environment:
      APP_PORT: ${APP_PORT:-8000}
    volumes:
      - ./static:/app/static
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
    command: ["daphne", "-b", "0.0.0.0", "-p", "${APP_PORT:-8000}", "Omnic_Clipper.asgi:application"]
    