# Generated by Django 5.1 on 2024-10-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioexampleimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='PricingImage',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioExampleImage',
        ),
    ]
