# Generated by Django 5.1 on 2024-10-13 17:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='details_text_editor',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
