# Generated by Django 5.1 on 2024-12-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_details_text_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='keywords',
            field=models.CharField(default='', max_length=500),
        ),
    ]
