# Generated by Django 5.1 on 2024-12-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='keywords',
            field=models.TextField(default=''),
        ),
    ]
