# Generated by Django 5.1 on 2024-09-02 20:54

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_service_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='Service/cover_image/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='details_text_editor',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
