# Generated by Django 5.1 on 2024-09-02 21:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_service_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='details_text_editor',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
