# Generated by Django 5.1 on 2024-09-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_service_details_text_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='details_text_editor',
            field=models.CharField(max_length=255),
        ),
    ]
