# Generated by Django 5.1 on 2024-09-02 21:41

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_service_details_text_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='details_text_editor',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
