# Generated by Django 5.1 on 2024-10-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMmessage',
            new_name='ContactMessage',
        ),
    ]
