# Generated by Django 5.1 on 2024-10-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_contactmmessage_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='site',
            field=models.URLField(null=True),
        ),
    ]
