# Generated by Django 5.1 on 2024-10-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_contactmessage_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='site',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
