# Generated by Django 5.1 on 2026-03-20 10:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('file_link', models.URLField(null=True)),
                ('type', models.CharField(max_length=150)),
                ('duration', models.CharField(max_length=255, null=True)),
                ('service', models.CharField(max_length=255)),
                ('message', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
