# Generated by Django 5.1 on 2024-10-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='setvice',
            new_name='service',
        ),
        migrations.AlterField(
            model_name='order',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
