# Generated by Django 5.1 on 2024-10-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_setvice_order_service_alter_order_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
