# Generated by Django 5.1 on 2024-10-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_file_link_alter_order_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='appointment',
        ),
        migrations.AddField(
            model_name='order',
            name='duration',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
