# Generated by Django 5.1 on 2024-12-05 08:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_pagecontent_image_alter_pagecontent_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(choices=[('home', 'home'), ('service', 'service'), ('price', 'price'), ('sample', 'sample'), ('about', 'about'), ('quote', 'quote'), ('blog', 'blog')], max_length=255)),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
