# Generated by Django 5.1 on 2024-12-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='title',
            field=models.CharField(default='Omnic Cliper', max_length=255),
        ),
    ]
