# Generated by Django 5.1 on 2024-12-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_metadata_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='key',
            field=models.CharField(choices=[('home', 'home'), ('service', 'service'), ('price', 'price'), ('sample', 'sample'), ('about', 'about'), ('quote', 'quote'), ('blog', 'blog')], max_length=255),
        ),
    ]
